# Generated by Django 5.2.6 on 2025-11-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dadjokes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
