# Generated by Django 5.2.6 on 2025-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voter",
            name="voter_score",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
