# Generated by Django 5.2.6 on 2025-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_voter_voter_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="apartment_number",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v20state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21primary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v21town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v22general",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="v23town",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="voter",
            name="voter_id_number",
            field=models.CharField(),
        ),
    ]
