# Generated by Django 5.2.6 on 2025-10-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_post_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-timestamp"]},
        ),
    ]
