# Generated by Django 5.2.6 on 2025-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="satus",
            field=models.TextField(default="availabe"),
        ),
    ]
