# Generated by Django 5.2.6 on 2025-11-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_product_satus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
