# Generated by Django 5.2.6 on 2025-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="satus",
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(default="available", max_length=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.TextField(default="unseen"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
