# Generated by Django 5.2.6 on 2025-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="status",
            field=models.TextField(default="pending"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
